### ISSUE TITLE
World Start on Venus

### ISSUE THREAD

**Issue by Flow86** [Elmotrix/TerraformingMod#4]
Hi,

when you have an active Terraforming Mod, the world start on Venus is broken since you start with >1200°C . You literally burn away after a few seconds.

Is there a way to mitigate this?

**Comment by Nevcairiel** [comment]
I've submitted a temporary fix for this in #5, but ultimately the math will need some re-jiggering to properly work with the new solar values on planets.

**Comment by Nevcairiel** [comment]
Elmo did all the math rejiggering, so hopefully the behavior on Venus and Vulcan should be just fine now!

**Comment by Flow86** [comment]
Its better, but still a bit hot (around >500° instead of ~460° or so) but at least you don't die on start :-)
